M48
; DRILL file {KiCad 9.0.2} date 2025-06-27T21:47:47+0100
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-06-27T21:47:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1378
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1496
%
G90
G05
T1
X5.7882Y-3.317
X6.8512Y-3.317
T2
X6.674Y-2.9626
T3
X5.735Y-2.125
X6.3256Y-5.52
X7.97Y-2.455
T4
X7.1806Y-2.1975
T5
X6.3197Y-3.7107
M30
